### PR TITLE
updated markers on map, with using ARCGIS Map

### PR DESCRIPTION
**Pull request by melimore86**
removed leaflet map, issues with markers now, and added Steve ArcGIS map, edited the text. will also be updating the landings and wq data in Shiny App.

### CODE REVIEW

**Comment by billpine** [comment]
looks good

**Comment by billpine** [comment]
approved

**Comment by billpine** [comment]
looks good

**Review by billpine — COMMENTED** [review]
looks good

**Comment by billpine** [comment]
ok

**Comment by melimore86** [comment]
did you go into review it and approve the merge? This pull request hasn't been completed.

**Review by billpine — APPROVED** [review]
ok these changes are approved

**Pull request merged**
